export function courseClasses(lab,files) {
  const code=Object.entries(files).filter(([name])=>name.endsWith('.js') && name!=='game.js').map(([,source])=>source.replace(/^import .*;$/gm,'').replace('export default ','')).join('\n');
  return new Function('GameLab',code+'\nreturn {Health,Experience,XpOrb,UpgradeController,PauseController,PlayerController,Weapon,Wallet,RunController,RunClock};')(lab);
}
export function runConformance(lab,course,id) {
  const games=[];
  const game=(setup=()=>{})=>{class Scene extends lab.Game {onCreate(){setup(this);}}const g=new Scene();g.canvas=new lab.Canvas(document.createElement('canvas'));g.canvas.resize(640,360);g.start();games.push(g);return g;};
  const obj=(g,name,x=0,y=0,parts=[])=>{const o=g.createObject(name);o.setPosition(x,y);for(const c of parts)o.addComponent(c);return o;};
  const advance=(g,time)=>{while(time>1e-9){const dt=Math.min(.1,time);g.step(dt);time-=dt;}};
  const point=o=>[o.transform.x,o.transform.y];
  const bounds=(x,y,w,h)=>({left:x-w/2,top:y-h/2,right:x+w/2,bottom:y+h/2});
  const collider=(r=12,trigger=false)=>{const c=new lab.CircleCollider2D(r);c.isTrigger=trigger;return c;};
  const button=(g,name,x=0,y=0)=>obj(g,name,x,y,[new lab.UITransform(100,40),new lab.Button(100,40)]).getComponent(lab.Button);
  try {
    switch(id) {
      case 'C01': {const g=game(g=>obj(g,'Shape',100,80,[new lab.ShapeRenderer(40,20,'#fff')]));g.step(0);const c=g.canvas.commands.find(c=>c.op==='rect');return {bounds:bounds(c.x,c.y,c.width,c.height)};}
      case 'C02': {const g=game(g=>{const o=obj(g,'Player',100,80,[new lab.Sprite(lab.Assets.PLAYER01,32,32),new lab.Collider2D(32,32)]);o.transform.scale.set(2,2);});g.step(0);const o=g.find('Player'),c=g.canvas.commands.find(c=>c.op==='sprite'),p=o.getComponent(lab.Collider2D);return {visualBounds:bounds(c.x,c.y,c.width*Math.abs(c.scaleX),c.height*Math.abs(c.scaleY)),colliderBounds:bounds(o.transform.x,o.transform.y,p.width,p.height)};}
      case 'C03':case 'C04': {class Move extends lab.Component {onUpdate(){this.requireComponent(lab.CharacterController2D).move(1,id==='C04'?1:0);}}const g=game(g=>obj(g,'P',100,100,[collider(),new lab.CharacterController2D(),new Move()]));advance(g,1);const p=g.find('P');return id==='C03'?{position:point(p),worldElapsed:g.time.elapsed}:{position:point(p),travelDistance:Math.hypot(p.transform.x-100,p.transform.y-100)};}
      case 'C05': {const g=game();g.step(.4);let valid=true;for(const value of [-1,NaN,Infinity]){const t=g.time.elapsed;let error;try{g.step(value);}catch(e){error=e;}valid&&=Boolean(error?.message)&&g.time.elapsed===t;}return {acceptedStepDelta:g.time.deltaTime,acceptedUnscaledDelta:g.time.unscaledDeltaTime,acceptedElapsed:g.time.elapsed,invalidInputs:valid?'descriptive errors without state mutation':'invalid step mutated state'};}
      case 'C06': {const log=[];class Probe extends lab.Component {onCreate(){log.push('onCreate');}onTrigger(){log.push('onTrigger');}}class Scene extends lab.Game {onCreate(){obj(this,'Sensor',100,100,[collider(16,true)]);}onUpdate(){if(!this.find('Target'))obj(this,'Target',100,100,[collider(16),new lab.ShapeRenderer(10,10,'#ff0000'),new Probe()]);}}const g=new Scene();g.canvas=new lab.Canvas(document.createElement('canvas'));g.canvas.resize(640,360);g.start();games.push(g);g.step(.1);const first=[...log],rendered=g.canvas.commands.some(c=>c.color==='#ff0000');g.step(.1);return {spawnedTargetStep1Log:first,spawnedTargetStep2Log:log,spawnedTargetStep1Rendered:rendered};}
      case 'C07':case 'C08':case 'C09': {const counts={A:{collision:0,trigger:0},B:{collision:0,trigger:0}};class Probe extends lab.Component {onCollision(){counts[this.gameObject.name].collision++;}onTrigger(){counts[this.gameObject.name].trigger++;}}class Move extends lab.Component {onUpdate(){this.requireComponent(lab.CharacterController2D).move(1,0,100);}}const g=game(g=>{const a=obj(g,'A',100,100,[new lab.Collider2D(32,32),new lab.CharacterController2D(),new Probe()]);const b=obj(g,'B',id==='C08'?140:110,100,[new lab.Collider2D(32,32),new lab.CharacterController2D(),new Probe()]);if(id==='C08'){a.getComponent(lab.Collider2D).isTrigger=true;a.addComponent(new Move());}if(id==='C09'){a.getComponent(lab.Collider2D).layer=1;a.getComponent(lab.Collider2D).mask=2;b.getComponent(lab.Collider2D).layer=2;b.getComponent(lab.Collider2D).mask=0;}});g.step(.1);if(id==='C07')return {onCollisionCounts:{A:counts.A.collision,B:counts.B.collision},onTriggerCounts:{A:counts.A.trigger,B:counts.B.trigger}};if(id==='C08')return {sensorPosition:point(g.find('A')),sensorCollisionCount:counts.A.collision,sensorTriggerCount:counts.A.trigger};return {contactCallbacks:counts.A.collision+counts.B.collision+counts.A.trigger+counts.B.trigger,blockingResolution:g.find('A').transform.x!==100};}
      case 'C10': {const g=game(g=>{obj(g,'CA',0,0,[collider(10)]);obj(g,'CB',20,0,[collider(10)]);obj(g,'BA',0,0,[new lab.Collider2D(20,20)]);obj(g,'BB',20,0,[new lab.Collider2D(20,20)]);});return {circleContact:g.physics.overlaps(g.find('CA'),g.find('CB')),boxContact:g.physics.overlaps(g.find('BA'),g.find('BB'))};}
      case 'C11':case 'C12': {let creates=0,updates=0,destroys=0,subsequent=0;class Destroyer extends lab.Component {onCreate(){creates++;}onUpdate(){updates++;}onTrigger(){this.gameObject.destroy();}onDestroy(){destroys++;}}class After extends lab.Component {onTrigger(){subsequent++;}}let target;const g=game(g=>{target=obj(g,'Target',100,100,[collider(16,true),new lab.ShapeRenderer(10,10,'#ff0000'),new Destroyer(),new After()]);if(id==='C12')target.destroy();else for(let i=0;i<3;i++)obj(g,'Sensor'+i,100,100,[collider(16,true)]);});g.step(.1);if(id==='C12')return {onCreateCount:creates,onUpdateCount:updates,onDestroyCount:destroys,renderCommandsForTarget:g.canvas.commands.filter(c=>c.color==='#ff0000').length};g.step(.1);return {subsequentTargetCallbacks:subsequent,onDestroyCountPerInitializedComponent:destroys,targetInNextFrame:g.getObjects().includes(target)};}
      case 'C13':case 'C14': {const g=game(g=>{const p=obj(g,'Target',600,400,[new lab.Sprite(lab.Assets.PLAYER01,32,32)]);obj(g,'Camera',0,0,[new lab.Camera2D()]).getComponent(lab.Camera2D).follow(p);if(id==='C14'){obj(g,'Ground',0,0,[new lab.TileMap(lab.Assets.GRASS,32)]);const h=obj(g,'HUD',12,12,[new lab.UITransform(200,18),new lab.TextRenderer('HUD',16,'#fff')]);h.getComponent(lab.UITransform).anchor='TOP_LEFT';}});g.step(0);const c=g.find('Camera').getComponent(lab.Camera2D),screen=c.worldToScreen(new lab.Vector2(600,400)),view=c.getView();if(id==='C13')return {viewTopLeft:[view.x,view.y],targetScreenPosition:[screen.x,screen.y]};const world=c.screenToWorld(screen);return {screen:[screen.x,screen.y],worldRoundtrip:[world.x,world.y],tilemapSpace:g.canvas.commands.some(c=>c.op==='tilemap')?'world':'missing',hudSpace:g.canvas.commands.find(c=>c.text==='HUD')?.x===112?'screen':'world'};}
      case 'C15':case 'C16': {const g=game(g=>{const o=obj(g,'UI',id==='C15'?12:-12,12,[new lab.UITransform(id==='C15'?200:100,id==='C15'?18:30)]);o.getComponent(lab.UITransform).anchor=id==='C15'?'TOP_LEFT':'TOP_RIGHT';obj(g,'Camera',0,0,[new lab.Camera2D()]);});const ui=g.find('UI').getComponent(lab.UITransform),first=ui.getBounds();if(id==='C16'){g.canvas.resize(800,450);return {firstBounds:first,secondBounds:ui.getBounds()};}const center=ui.getCenter();g.find('Camera').getComponent(lab.Camera2D).offsetX=200;const next=ui.getBounds();return {bounds:first,center:[center.x,center.y],unchangedAfterCamera:JSON.stringify(first)===JSON.stringify(next)};}
      case 'C17': {const bar=new lab.ProgressBar(200,18),fractions=[];for(const [v,m]of[[3,5],[6,5],[-1,5],[3,0]]){bar.setValue(v,m);fractions.push(bar.getProgress()/100);}return {fractions};}
      case 'C18': {let uiUpdates=0,contacts=0;class Timer extends lab.Component {remaining=.3;onUpdate(d){this.remaining-=d;}onCollision(){contacts++;}}class UI extends lab.Component {constructor(){super();this.updateMode='UI';}onUpdate(){uiUpdates++;}}const g=game(g=>{const p=obj(g,'P',100,100,[collider(),new course.Health(3,.5),new Timer(),new UI()]);p.getComponent(course.Health).invulnerability=.5;obj(g,'Enemy',100,100,[collider()]);});g.time.elapsed=1;g.time.unscaledElapsed=1;g.pause();advance(g,1);const p=g.find('P');return {worldElapsed:g.time.elapsed,unscaledElapsed:g.time.unscaledElapsed,hp:p.getComponent(course.Health).currentHealth,invulnerabilityRemaining:p.getComponent(course.Health).invulnerability,weaponRemaining:p.getComponent(Timer).remaining,worldContactCallbacks:contacts,uiUpdates};}
      case 'C19':case 'C20':case 'C21':case 'C22':case 'C23': {const g=game(g=>obj(g,'P',0,0,[collider()])),p=g.find('P');let complete=0;if(id==='C23'){lab.Tweens.rotation(p,Math.PI*2,1);advance(g,.5);return {rotation:p.transform.rotation};}if(id==='C21'){const t=lab.Tweens.position(p,100,40,0).onComplete(()=>complete++);g.step(.1);return {position:point(p),completed:t.completed,completionCallbackCount:complete};}const old=lab.Tweens.position(p,100,0,1).onComplete(()=>complete++);advance(g,.25);if(id==='C19')return {position:point(p),completed:old.completed};if(id==='C20'){lab.Tweens.position(p,200,0,1);advance(g,.5);return {position:point(p),oldTweenCancelled:old.cancelled,oldTweenCompletionCallbacks:complete};}p.transform.visualOffset.set(3,4);const shake=lab.Tweens.shake(p,8,1);g.step(0);old.cancel();shake.cancel();advance(g,.5);return {position:point(p),visualOffset:[p.transform.visualOffset.x,p.transform.visualOffset.y],completionCallbackCount:complete,colliderGeometry:p.getComponent(lab.CircleCollider2D).radius===12?'unchanged':'changed'};}
      case 'C24':case 'C25':case 'C26': {const g=game(g=>{obj(g,'A',0,0,[new course.Health(3,.5)]);obj(g,'B',50,0,[new course.Health(3,.5)]);}),a=g.find('A').getComponent(course.Health),b=g.find('B').getComponent(course.Health);if(id==='C25'){const accepted=[a.damage(1),b.damage(1),a.damage(1)];return {A_Hp:a.currentHealth,B_Hp:b.currentHealth,accepted};}if(id==='C26'){let deathEvents=0,xpDrops=0;a.currentHealth=1;a.onDeath(()=>{deathEvents++;xpDrops++;obj(g,"XP",0,0,[new course.XpOrb(5)]);});a.damage(2);a.damage(2);a.heal(3);return {hp:a.currentHealth,isDead:a.dead,deathEvents,xpDrops};}const accepted=[a.damage(1)],hp=[a.currentHealth];advance(g,.49);accepted.push(a.damage(1));hp.push(a.currentHealth);advance(g,.01);accepted.push(a.damage(1));hp.push(a.currentHealth);return {damageAccepted:accepted,hpAfterAttempts:hp};}
      case 'C27':case 'C28':case 'C29': {const hits={owner:0,pickup:0,A:0,B:0};class Hit extends lab.Component {onTrigger(other){hits[other.name]++;const hp=other.getComponent(course.Health);if(hp)hp.damage(1);}}let shot;const g=game(g=>{const owner=obj(g,'owner',25,100,[collider(4)]);obj(g,'pickup',45,100,[collider(4,true)]);const a=obj(g,'A',100,100,[new lab.Collider2D(2,32),new course.Health(3,0)]);a.getComponent(lab.Collider2D).layer=2;const b=obj(g,'B',125,100,[collider(4),new course.Health(3,0)]);b.getComponent(lab.Collider2D).layer=2;shot=obj(g,'Shot',20,100,[new lab.Projectile2D(1,0,id==='C29'?100:1200,id==='C29'?.025:2,owner),new Hit()]);const motion=shot.getComponent(lab.Projectile2D);motion.hitLayers=2;motion.maxHits=id==='C28'?2:1;if(id==='C29')for(const o of g.getObjects())if(o!==shot)o.destroy();});g.step(.1);if(id==='C29')return {finalPosition:point(shot),destroyed:shot.destroyed};if(id==='C28')return {ownerHits:hits.owner,pickupHits:hits.pickup,enemyAHits:hits.A,enemyBHits:hits.B,projectileDestroyed:shot.destroyed,totalAcceptedHits:hits.A+hits.B};return {targetHp:g.find('A').getComponent(course.Health).currentHealth,hitCallbacks:hits.A,projectileDestroyed:shot.destroyed};}
      case 'C30': {const g=game(g=>{obj(g,'inactive',1,0,[collider(1)]).active=false;const a=obj(g,'A',10,0,[collider(1)]),b=obj(g,'B',-10,0,[collider(1)]);a.getComponent(lab.Collider2D).layer=b.getComponent(lab.Collider2D).layer=2;});g.step(0);return {resultId:g.physics.findNearest(0,0,20,2).id};}
      case 'C31': {const g=game(g=>obj(g,'P',0,0,[new course.Experience(),new course.PauseController(),new course.UpgradeController(),new course.PlayerController(),new course.Weapon(),new course.Wallet()])),p=g.find('P'),xp=p.getComponent(course.Experience),menu=p.getComponent(course.UpgradeController);xp.add(35);menu.onUpdate();const afterGrant={level:xp.level,xp:xp.xp,pendingChoices:xp.pendingChoices,paused:g.isPaused()};menu.select(1);const afterFirst={pendingChoices:xp.pendingChoices,paused:g.isPaused()};menu.select(2);return {afterGrant,afterFirst,afterSecond:{pendingChoices:xp.pendingChoices,paused:g.isPaused()}};}
      case 'C32': {const g=game(g=>{obj(g,'P',0,0,[new course.Experience()]);obj(g,'Pickup',0,0,[new course.XpOrb(5)]);});const xp=g.find('P').getComponent(course.Experience),pick=g.find('Pickup');xp.onTrigger(pick);const first=xp.totalXp;xp.onTrigger(pick);return {playerXp:xp.totalXp,pickupDestroyed:pick.destroyed,grantCount:xp.totalXp===first?1:2};}
      case 'C33': {let n=0;const g=game(g=>{const b=button(g,'Button');b.onClick=()=>n++;});g.pause();const b=g.find('Button').getComponent(lab.Button);b.focus();g.input.setPointer(320,180);g.input.setMouseButton(0,true);g.step(.1);g.input.setMouseButton(0,false);g.step(.1);const pointerActivations=n;for(let i=0;i<3;i++){g.input.setKey('Enter',true);g.step(.1);}g.input.setKey('Enter',false);g.step(.1);return {pointerActivations,keyboardActivations:n-pointerActivations,worldAdvanced:g.time.elapsed>0};}
      case 'C34': throw new Error('C34 requires the real scene-id guarded queued activation dispatcher; stale button references are not an equivalent test.');
      case 'C35': {const r=new lab.Random(1),numbers=Array.from({length:5},()=>r.next());return {uint32:numbers.map(n=>n*4294967296),numbers};}
      case 'C38': {const events=[];class Move extends lab.Component {onCreate(){events.push('create');}onUpdate(d){this.transform.x+=120*d;events.push('update');}}const g=game(g=>obj(g,'P',100,80,[new lab.ShapeRenderer(40,20,'#fff'),new Move()]));advance(g,.5);const c=g.canvas.commands.find(c=>c.op==='rect');return {position:point(g.find('P')),events,geometry:[c.x,c.y,c.width,c.height]};}
      case 'C39':case 'C40': {class Move extends lab.Component {onUpdate(){this.requireComponent(lab.CharacterController2D).move(1,id==='C40'?1:0,600);}}const g=game(g=>{obj(g,'P',100,100,[collider(12),new lab.CharacterController2D(),new Move()]);obj(g,'Wall',140,110,[new lab.Collider2D(2,400)]);});g.step(.1);const p=g.find('P');return {position:point(p),crossedWall:p.transform.x>127+1e-6};}
      case 'C41': {const sequence=[];let chosen='',activations=0,world=0;class Action extends lab.Component {onUpdate(){if(this.game.input.isKeyReleased('Enter'))world++;}}const g=game(g=>{obj(g,'World',0,0,[new Action()]);for(const name of ['A','B','C']){const b=button(g,name);b.onClick=()=>{chosen=name;activations++;for(const other of g.getObjects())for(const button of other.getComponents(lab.Button)){button.blur();button.enabled=false;}g.resume();};}});g.pause();g.find('A').getComponent(lab.Button).focus();const focused=()=>g.getObjects().find(o=>o.getComponent(lab.Button)?.isFocused())?.name;sequence.push(focused());for(let i=0;i<3;i++){g.input.setKey('Tab',true);g.step(.1);sequence.push(focused());g.input.setKey('Tab',false);g.step(.1);}g.input.setKey('Shift',true);g.input.setKey('Tab',true);g.step(.1);sequence.push(focused());g.input.setKey('Tab',false);g.input.setKey('Shift',false);g.step(.1);g.input.setKey('Enter',true);g.step(.1);g.input.setKey('Enter',false);g.step(.1);const closing=world;g.step(.1);return {focusSequence:sequence,chosenButton:chosen,activationCount:activations,worldActionInClosingFrame:closing,closedButtonsFocused:g.getObjects().some(o=>o.getComponent(lab.Button)?.isFocused())};}
      case 'C42': {const g=game(g=>obj(g,'Run',0,0,[new course.RunController()])),run=g.find('Run').getComponent(course.RunController);run.start();g.step(0);run.player.getComponent(course.Health).currentHealth=1;run.player.getComponent(course.RunClock).elapsed=119.95;g.time.elapsed=119.95;class Lethal extends lab.Component {onTrigger(other){other.getComponent(course.Health)?.damage(1);}}obj(g,'Enemy',run.player.transform.x,run.player.transform.y,[collider(12,true),new Lethal()]);g.step(.05);return {state:run.state,lostPanels:g.canvas.commands.filter(c=>c.text?.startsWith('LOST')).length,wonPanels:g.canvas.commands.filter(c=>c.text?.startsWith('WON')).length,worldPaused:g.isPaused()};}
      case 'C43': {class Damage extends lab.Component {onTrigger(other){other.getComponent(course.Health)?.damage(2);}}class View extends lab.Component {constructor(){super();this.updateMode='UI';}onLateUpdate(){const hp=this.requireComponent(course.Health);this.requireComponent(lab.ProgressBar).setValue(hp.currentHealth,hp.maxHealth);}}const g=game(g=>{obj(g,'P',100,100,[collider(),new course.Health(5,0),new lab.ProgressBar(200,18),new View()]);obj(g,'Damage',100,100,[collider(12,true),new Damage()]);});g.step(.1);const p=g.find('P');return {playerHp:p.getComponent(course.Health).currentHealth,displayedHpFraction:p.getComponent(lab.ProgressBar).getProgress()/100,extraFrameRequired:false};}
      default: throw new Error(`${id} is a host-adapter/package scenario, not an engine step.`);
    }
  } finally {for(const g of games)g.dispose();}
}



